//! Integrated terminal.
//!
//! A real PTY running the user's real login shell, so their prompt, aliases,
//! functions and completions all work exactly as they do in Terminal.app. The
//! previous version spawned a bare non-login `zsh`, which skipped ~/.zshrc
//! entirely — that is why completion appeared "missing".

use crate::shellenv;
use portable_pty::{native_pty_system, CommandBuilder, MasterPty, PtySize};
use serde::Serialize;
use std::collections::HashMap;
use std::io::{Read, Write};
use std::path::PathBuf;
use std::sync::Mutex;
use tauri::{AppHandle, Emitter, State};

#[derive(Default)]
pub struct Terminals(pub Mutex<HashMap<String, Term>>);

pub struct Term {
    master: Box<dyn MasterPty + Send>,
    writer: Box<dyn Write + Send>,
    child: Box<dyn portable_pty::Child + Send + Sync>,
}

#[derive(Serialize, Clone)]
struct Chunk<'a> {
    id: &'a str,
    data: String,
}

const AUTOSUGGEST: &[&str] = &[
    "/opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh",
    "/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh",
];
const SYNTAX: &[&str] = &[
    "/opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh",
    "/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh",
];

/// Build a ZDOTDIR whose .zshrc sources the user's own config first, then layers
/// on completion and inline suggestions. Their file is never modified.
fn zdotdir() -> Option<PathBuf> {
    let home = std::env::var("HOME").ok()?;
    let dir = std::env::temp_dir().join("claude-ide-zdotdir");
    std::fs::create_dir_all(&dir).ok()?;

    fn found(list: &[&'static str]) -> Option<&'static str> {
        list.iter().find(|p| PathBuf::from(*p).exists()).copied()
    }
    let sugg = found(AUTOSUGGEST);
    let synx = found(SYNTAX);

    let mut rc = String::new();
    rc.push_str("# Generated by Claude IDE. Your own ~/.zshrc is sourced untouched below.\n");
    rc.push_str(&format!("export ZDOTDIR={home}\n"));
    rc.push_str(&format!("[ -f {home}/.zshrc ] && source {home}/.zshrc\n"));
    rc.push_str(
        r#"
autoload -Uz compinit && compinit -C -u 2>/dev/null
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors ''
setopt AUTO_CD AUTO_PUSHD HIST_IGNORE_DUPS SHARE_HISTORY
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward
"#,
    );

    match sugg {
        Some(p) => {
            rc.push_str(&format!("source {p}\n"));
            rc.push_str("ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#6b6b76'\nbindkey '^[[C' forward-char\n");
        }
        None => rc.push_str(
            r#"
# Inline suggestions need the zsh-autosuggestions plugin, which is not installed.
if [ ! -f "${TMPDIR:-/tmp}/claude-ide-suggest-hint" ]; then
  print -P "%F{240}Claude IDE: for inline suggestions run%f %F{215}brew install zsh-autosuggestions zsh-syntax-highlighting%f"
  touch "${TMPDIR:-/tmp}/claude-ide-suggest-hint" 2>/dev/null
fi
"#,
        ),
    }
    if let Some(p) = synx {
        // Syntax highlighting must be sourced last to wrap the final widgets.
        rc.push_str(&format!("source {p}\n"));
    }

    std::fs::write(dir.join(".zshrc"), rc).ok()?;
    Some(dir)
}

#[tauri::command]
pub fn pty_open(
    app: AppHandle,
    state: State<Terminals>,
    id: String,
    cwd: String,
    rows: u16,
    cols: u16,
) -> Result<(), String> {
    let mut map = state.0.lock().map_err(|e| e.to_string())?;
    if map.contains_key(&id) {
        return Ok(());
    }

    let pair = native_pty_system()
        .openpty(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
        .map_err(|e| e.to_string())?;

    let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/zsh".into());
    let mut cmd = CommandBuilder::new(&shell);
    // Login + interactive: the combination that actually loads a user's config.
    cmd.args(["-l", "-i"]);
    cmd.cwd(&cwd);
    cmd.env("PATH", shellenv::login_path());
    cmd.env("TERM", "xterm-256color");
    cmd.env("COLORTERM", "truecolor");
    cmd.env("LANG", std::env::var("LANG").unwrap_or_else(|_| "en_US.UTF-8".into()));
    cmd.env("CLAUDE_IDE", "1");

    if shell.ends_with("zsh") {
        if let Some(dir) = zdotdir() {
            cmd.env("ZDOTDIR", dir.to_string_lossy().to_string());
        }
    }

    let child = pair.slave.spawn_command(cmd).map_err(|e| e.to_string())?;
    drop(pair.slave);

    let mut reader = pair.master.try_clone_reader().map_err(|e| e.to_string())?;
    let writer = pair.master.take_writer().map_err(|e| e.to_string())?;

    {
        let app = app.clone();
        let id = id.clone();
        std::thread::spawn(move || {
            let mut buf = [0u8; 8192];
            loop {
                match reader.read(&mut buf) {
                    Ok(0) | Err(_) => break,
                    Ok(n) => {
                        let data = String::from_utf8_lossy(&buf[..n]).to_string();
                        let _ = app.emit("pty", Chunk { id: &id, data });
                    }
                }
            }
            let _ = app.emit("pty-closed", &id);
        });
    }

    map.insert(id, Term { master: pair.master, writer, child });
    Ok(())
}

#[tauri::command]
pub fn pty_write(state: State<Terminals>, id: String, data: String) -> Result<(), String> {
    let mut map = state.0.lock().map_err(|e| e.to_string())?;
    let term = map.get_mut(&id).ok_or("no such terminal")?;
    term.writer.write_all(data.as_bytes()).map_err(|e| e.to_string())?;
    term.writer.flush().map_err(|e| e.to_string())
}

#[tauri::command]
pub fn pty_resize(state: State<Terminals>, id: String, rows: u16, cols: u16) -> Result<(), String> {
    let map = state.0.lock().map_err(|e| e.to_string())?;
    let term = map.get(&id).ok_or("no such terminal")?;
    term.master
        .resize(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub fn pty_close(state: State<Terminals>, id: String) -> Result<(), String> {
    let mut map = state.0.lock().map_err(|e| e.to_string())?;
    if let Some(mut term) = map.remove(&id) {
        let _ = term.child.kill();
        let _ = term.child.wait();
    }
    Ok(())
}
